### ISSUE TITLE
Running without arguments raises an exception

### ISSUE THREAD

**Issue by dgzlopes** [google/slo-generator#120]
Running `slo-generator` without arguments raises a `FileNotFoundError` exception.

I think this exception should be handled! Also, probably it's interesting to show the help msg if `slo-generator` is run like that.

Version: 1.5.0
Example:
```bash
➜  slo-generator git:(master) slo-generator   
DEBUG: 0
Traceback (most recent call last):
  File "/home/dgzlopes/.pyenv/versions/3.8.3/bin/slo-generator", line 8, in <module>
    sys.exit(main())
  File "/home/dgzlopes/.pyenv/versions/3.8.3/lib/python3.8/site-packages/slo_generator/cli.py", line 36, in main
    cli(args)
  File "/home/dgzlopes/.pyenv/versions/3.8.3/lib/python3.8/site-packages/slo_generator/cli.py", line 57, in cli
    eb_policy = utils.parse_config(eb_path)
  File "/home/dgzlopes/.pyenv/versions/3.8.3/lib/python3.8/site-packages/slo_generator/utils.py", line 94, in parse_config
    with open(path) as config:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dgzlopes/workspace/k6/slo-generator/error_budget_policy.yaml'
```

**Comment by ocervell** [comment]
You can run `slo-generator` without arguments if you have an `error_budget_policy.yaml` and SLO configs in the current folder. Isn't the native exception explicit enough ?

**Comment by dgzlopes** [comment]
Yup! I agree. Just thought that for a newcomer, probably it's not a good experience to get a traceback when you run `slo-generator`.

But it's OK to have it un-handled :)

**Comment by ocervell** [comment]
Point taken, we might need to give a more user-friendly message when this is the case.

**Comment by ocervell** [comment]
Small update: this will be fixed when `v2` is released as we're switching to `Click` library for the CLI that handles this case automatically.
