### ISSUE TITLE
Build fails on Python 3.10 due to the `collections` module

### ISSUE THREAD

**Issue by ocervell** [google/slo-generator#180]
`gcloud` fails to load on Python 3.10:
```
ERROR: gcloud failed to load: module 'collections' has no attribute 'Mapping'
```

Also, lint and unit tests fail to run on Python 3.10, example run here:
https://github.com/google/slo-generator/runs/4247056898?check_suite_focus=true

**Comment by lvaylet** [comment]
Looks like it is a known issue which got fixed a couple of days ago ((Mar 17, 2022) in release 377.0.0: https://issuetracker.google.com/issues/202172882?pli=1

Let me install Python 3.10.2 and confirm `make lint` and `make unit` complete successfully.

**Comment by lvaylet** [comment]
`make lint` still fails but I am not surprised as the issue with `gcloud` is completely independent:

```bash
(venv10.3) $ make lint
flake8 --ignore=E302,E203,E261 "slo_generator"/ --max-line-length=80
flake8 --ignore=E302,E203,E261,E402 tests/ --max-line-length=80
find ./"slo_generator" ./tests -name \*.py | xargs pylint --rcfile .pylintrc --ignore-patterns=test_.*?py
************* Module slo_generator.utils
slo_generator/utils.py:422:24: E1101: Module 'collections' has no 'Mapping' member (no-member)

------------------------------------------------------------------
Your code has been rated at 9.97/10 (previous run: 9.97/10, +0.00)

make: *** [Makefile:81: pylint] Error 123
```

`make unit` fails too. Again, this is expected:

```bash
(venv10.3) $ make unit
[...]
  File "/home/laurent/workspace/github/google/slo-generator/venv3.10/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
make: *** [Makefile:69: unit] Error 1
```

**Comment by lvaylet** [comment]
Upon investigation, there is an easy fix (replace `import collections` with `import collections.abc` and `collections.Mapping` with `collections.abc.Mapping` at call sites) but it requires updating the `nose` library itself. Unfortunately, `nose` is no longer being maintained and the latest 1.3.7 version is explicitly not compatible with Python >= 3.10:

- [Nose is incompatible with Python >= 3.10 #95](https://github.com/xlcnd/isbnlib/issues/95)
- [nose is unmaintained and will stop working under future versions of Python #942
](https://github.com/minio/minio-py/issues/942)

And the [official website](https://nose.readthedocs.io/en/latest/) starts with:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using [Nose2](https://github.com/nose-devs/nose2), [py.test](http://pytest.org/), or just plain unittest/unittest2.

@ocervell WDYT? Is this a good opportunity to move to [`py.test`](https://docs.pytest.org/en/7.1.x/)?

**Comment by ocervell** [comment]
@lvaylet  Sounds good to me. Had no idea nose was going to be discontinued...

**Comment by lvaylet** [comment]
Fixed by:
- https://github.com/google/slo-generator/pull/256
- https://github.com/google/slo-generator/pull/254
