### ISSUE TITLE
BigQuery Exporter: column alerting_burn_rate_threshold always null

### ISSUE THREAD

**Issue by Eraac** [google/slo-generator#184]
As the title say, if you use the bigquery exporter, the column `alerting_burn_rate_threshold` is always null (instead of having the value in the `error_budget_policies.<name>.steps[x].burn_rate_threshold`

I suspect something wrong with the name in the configuration file and the column name

**Comment by ocervell** [comment]
@clement-pruvot did you observe this on your env too ?

**Comment by ocervell** [comment]
fixed by https://github.com/google/slo-generator/pull/201
