### ISSUE TITLE
events_count labels in prometheus exporter

### ISSUE THREAD

**Issue by djetelina** [google/slo-generator#186]
Hi,

did I misconfigure something, or is it intended for prometheus exporter to export events count as labels? This would lead to extremely high cardinality, which is very bad for prometheus.

**Comment by ocervell** [comment]
Without this, the `events_count` metric is pretty useless (it was used to split good / bad labels) but you argument about cardinality makes sense.

For now I suggest you disable this metric by overriding the metrics block in your Prometheus exporter configuration blob like suggested [here](https://github.com/google/slo-generator/blob/master/docs/shared/metrics.md#override-config-advanced). The `metrics` block is used to specify only the metrics you want to keep.

**Comment by djetelina** [comment]
Thanks for the reply! I totally missed that configuration part and it solves the issue, more elegantly than just me dropping the labels :)
