### ISSUE TITLE
Error when sending consequence message

### ISSUE THREAD

**Issue by SanaZulfiqar73** [google/slo-generator#218]
Hello,

I am using prometheus as backend and exporting metrics using Prometheus-Pushgateway.
When sending SLO report to the exporter, I tried to export consequence message as metrics in [config.yaml](https://github.com/ocervell/slo-generator-gke/blob/master/config.yaml)
I am getting this error in the logs and not able to export the message:
` | PrometheusExporter "prometheus" failed. | ValueError: could not convert string to float: 'Last hour on track'`

**Comment by ocervell** [comment]
Hey @SanaZulfiqar73 ,
Metric values need to be integers, strings cannot be used as metric values. 
What are you trying to do exactly ?
