### ISSUE TITLE
Missing argument in API exporters

### ISSUE THREAD

**Issue by casmssm** [google/slo-generator#233]
Hi, I receiving this error on submit a SLI to compute in slo-generator[api] (version v2.0.1):

**TypeError: export() missing 1 required positional argument: 'exporters'**

My SLO yaml file content:

apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: metricscustom
  labels:
    service_name: metricscustom
    feature_name: metrics
    slo_name: availability
spec:
  description: 99.9% of Prometheus requests return a good HTTP code
  backend: prometheus/dev
  exporters: prometheus/dev
  method: query_sli
  service_level_indicator:
    expression: ...myexpression...
  goal: 0.999

**Comment by ocervell** [comment]
Please update to 2.2.0 👍
