### ISSUE TITLE
Document the format and syntax of filter for Cloud Monitoring exporter

### ISSUE THREAD

**Issue by ymotongpoo** [google/slo-generator#250]
In the [Cloud Monitoring provider](https://github.com/google/slo-generator/blob/master/docs/providers/cloud_monitoring.md) document, there's no descriptions on how to write filters correctly. It should include the link to [the document of filters for Cloud Monitoring v3 API](https://cloud.google.com/monitoring/api/v3/filters). It would be nicer if the provider document itself includes the getting started level description on how to write filters for Cloud Monitoring v3 API.

**Comment by lvaylet** [comment]
Hi @ymotongpoo, thanks a lot for reporting this and congratulations on submitting your first issue with the SLO Generator :-)

Have you checked the samples that ship for both the backend and the exporter? For example [samples/cloud_monitoring/slo_gae_app_availability.yaml](https://github.com/google/slo-generator/blob/master/samples/cloud_monitoring/slo_gae_app_availability.yaml) or [samples/cloud_monitoring/slo_lb_request_availability.yaml](https://github.com/google/slo-generator/blob/master/samples/cloud_monitoring/slo_lb_request_availability.yaml)?

Also, just to make sure we are on the same page, are we talking about the Cloud Monitoring [backend](https://github.com/google/slo-generator/blob/master/slo_generator/backends/cloud_monitoring.py) or the Cloud Monitoring [exporter](https://github.com/google/slo-generator/blob/master/slo_generator/exporters/cloud_monitoring.py) here? They have different purposes and different behaviors. Filters are definitely relevant for the backend, whose job is to query and retrieve time series. From my point of view, filters might be less relevant for the exporter, whose job is to write a time series with a predefined format.

**Comment by lvaylet** [comment]
On a side note, I am working on adding a Cloud Monitoring backend that supports MQL: https://github.com/google/slo-generator/pull/245. It is being reviewed by @ocervell.

**Comment by ymotongpoo** [comment]
@lvaylet Thank you for the comment.

> Have you checked the samples that ship for both the backend and the exporter?
Yes, they helped me to understand the YAML format better.

> Also, just to make sure we are on the same page, are we talking about the Cloud Monitoring [backend](https://github.com/google/slo-generator/blob/master/slo_generator/backends/cloud_monitoring.py) or the Cloud Monitoring [exporter](https://github.com/google/slo-generator/blob/master/slo_generator/exporters/cloud_monitoring.py) here?

Apologies for the confusion. I meant "backend" here. As soon as I looked into the implementation of `slo-generator`, I realized that it is calling Cloud Monitoring v3 API and it expects the filter format [documented here](https://cloud.google.com/monitoring/api/v3/filters), but I couldn't tell which format to follow without looking into the source code. I suppose this happens to the people as well who usually use Metrics Explorer and don't use Cloud Monitoring v3 API.

My suggestion here is just to encourage people to refer to [this document](https://cloud.google.com/monitoring/api/v3/filters) in the [Backend](https://github.com/google/slo-generator/blob/master/docs/providers/cloud_monitoring.md#backend) section for filter format and syntax.

> On a side note, I am working on adding a Cloud Monitoring backend that supports MQL: https://github.com/google/slo-generator/pull/245. It is being reviewed by @ocervell.

This is really cool! I also look forward it to be merged!

**Comment by lvaylet** [comment]
Sounds great! Do you fell comfortable creating the PR yourself? Then I can review it and your name will be added to the growing list of contributors 🙂

On a style note, we use semantic commit messages so your PR title will look like "docs: <your PR description>". No pressure though. We can change this anytime.

Let me know if you need help or if something is unclear.

**Comment by ymotongpoo** [comment]
Of course I'm happy to!

> On a style note, we use semantic commit messages so your PR title will look like "docs: ". No pressure though. We can change this anytime.

Roger that 👍
