### ISSUE TITLE
Fix set-output in Github Actions to be deprecated

### ISSUE THREAD

**Issue by k1rnt** [google/slo-generator#251]
Hi!

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
As per this URL, set-output of Github Actions is deprecated.

I would like to create a PR for a fix to this issue.
Thanks.

**Comment by lvaylet** [comment]
Hi @k1rnt, thanks for bringing this to our attention. Please go ahead and create the PR you have in mind.
