### ISSUE TITLE
Exporter of Cloud Monitoring failing by metrics read

### ISSUE THREAD

**Issue by casmssm** [google/slo-generator#288]
I've received some erros in quota of metric (ListMetricDesriptors AND CreateMetricDesriptors) with the following output:

ERROR - 429 Quota exceeded for quota metric 'Descriptor read requests' and limit 'Descriptor read requests per minute' of service 'monitoring.googleapis.com'

I ask for increase in this metric on GCP, but the operator answered with this pull request: https://github.com/google/slo-generator/pull/286

**Comment by lvaylet** [comment]
Hi @casmssm, I was indeed contacted by the Google Cloud support team regarding this issue. I will merge the PR today or tomorrow and release a new 2.3.2 version with the bug fix.

**Comment by lvaylet** [comment]
Hi @casmssm, 2.3.2 is available on:
- PyPi: https://pypi.org/project/slo-generator/
- Google Cloud Registry (GCR)]: gcr.io/slo-generator-ci-a2b4/slo-generator:2.3.2
