### ISSUE TITLE
Grafana Dashboard for SLO

### ISSUE THREAD

**Issue by Sharechat-Taran** [google/slo-generator#298]
Is there any doc or open source grafana dashboard which can used for the metric  generated by the generator?

**Comment by lvaylet** [comment]
Hi @Sharechat-Taran, and thanks for asking.

At the time of writing, I am not aware of any Grafana dashboard, both here on the repo or deployed internally by some users of the SLO Generator.

If you come up with a dashboard yourself, please feel free to share it here and document it, for example by opening a Pull Request.

**Comment by Sharechat-Taran** [comment]
@lvaylet Thanks for answering my question. 
Sure i will share dashboard when i will complete it.

**Comment by lvaylet** [comment]
Thanks a lot @Sharechat-Taran. I will now close this issue. Feel free to reopen it if you have more questions.
