### ISSUE TITLE
💡 [REQUEST] - Upgrade google-api-python-client

### ISSUE THREAD

**Issue by Lawouach** [google/slo-generator#349]
### Summary

This package has a strong pin for google-api-python-client to be under its 2.0 release. But that means we can't benefit from updates for that package and that causes issues when importing slo-generator alongside other libraries that require a more recent google-api-python-client.

Could google-api-python-client be updated?

### Basic Example

n/a

### Drawbacks

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lvaylet** [comment]
Hi @Lawouach, I agree this strong pin could prevent future updates. At the same time, it introduces stability and reproducibility into the SDLC.

@ocervell Do you recall a specific reason for this strong pin? Otherwise I will try removing it and confirm whether unit tests  complete successfully.

**Comment by Lawouach** [comment]
Fair point indeed.

I'm importing slo-generator as a library in one application which also use the GCP libraries. Right now, with slo-generator strict pinning, I cannot benefit from the client > 2.0 and since the 1.x branch isn't maintained any longer, I am worried about security patches I'm missing.

But I fully appreciate where you are coming from here.

**Comment by lvaylet** [comment]
@Lawouach I removed the strong pins entirely and unit tests complete successfully. Let me do a few more integration tests, especially with the Cloud Monitoring backend and exporter.

**Comment by Lawouach** [comment]
I really appreciate the effort on this!

**Comment by lvaylet** [comment]
I just confirmed there does not seem to be any conflict with the new package versions. I am able to query an App Engine Availability SLI with the Cloud Monitoring backend, then export the metrics to Cloud Monitoring and Pub/Sub with the two libraries that got updated too. So I'd say we are all set. I will move forward and merge the PR.

**Comment by Lawouach** [comment]
Great! This is much welcome. Will you be able to make a new release soon as well by chance?

**Comment by lvaylet** [comment]
I just released 2.5.0, mainly due to the support of OpenSearch. Two birds with one stone.

**Comment by Lawouach** [comment]
Fantastic. Thanks again!
