### ISSUE TITLE
Big query timestamp_human isn't correct

### ISSUE THREAD

**Issue by thollander** [google/slo-generator#39]
While looking at our last exports of SLO in Bigquery, we found that the `timestamp_human` isn't correct. 

Looking at 12.48 (Paris, France : **UTC+2**), it shows a time of 12.48 **UTC**
![image](https://user-images.githubusercontent.com/23191482/94363056-d491a380-00bf-11eb-8d4b-cb0581a2b2f8.png)

That leads to a gap in our Grafana graphs.

Not sure if we can configure this or if it's a problem in the management of the `get_human_time` function https://github.com/google/slo-generator/blob/3a63e6e9662a9ebd99ee57fc2085fe0d95545ca8/slo_generator/utils.py#L121

Thanks for your help !

**Comment by ocervell** [comment]
Hello @thollander,
I did a quick test for the function:
```
>>> from slo_generator.utils import get_human_time
>>> from time import time
>>> timestamp = time()
>>> get_human_time(timestamp)

'2020-09-28T11:12:43.773077Z'

**Comment by ocervell** [comment]
Ah, nevermind, fixed it in above PR. Will be releaesd with the next minor version.
