### ISSUE TITLE
Add "timezone" argument to custom the compute of human_timestamp

### ISSUE THREAD

**Issue by bkamin29** [google/slo-generator#40]
`slo-generator` export in BQ a human_timestamp.
By default the timezone is `Europe/Paris`.
We have to add an argument to be able to custom this timezone
Default have to be `UTC`

Created from https://github.com/GoogleCloudPlatform/professional-services/pull/522

**Comment by ocervell** [comment]
Hey @bkamin29 , I've merged #43 which addresses part of this issue: basically it gives you a human timestamp based on where slo-generator runs - do you think there should still be an option to manually set ?

**Comment by bkamin29** [comment]
We can keep this issue but with #43 it's not a priority no ?
In my case #43 is enough
