### ISSUE TITLE
🐛 [BUG] - latest releases aren't pushed into the GCR

### ISSUE THREAD

**Issue by bkamin29** [google/slo-generator#404]
### SLO Generator Version

v2.4.0

### Python Version

v2.4.0

### What happened?

It's seem we having an issue with the GCR, currently we aren't able to pull more recent than v2.4.0..

### What did you expect?

I suppose we have an issue when pushing latest image to the GCR, instead of GHCR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lvaylet** [comment]
Hi @bkamin29, thanks for reporting this. Can you share the output of your `docker pull` command, or the Cloud Run logs? I do see the images of `2.5.0` and `2.5.1` in the Google Container Registry. Also, which identity do you use to pull the images. One of the three Service Accounts that are allowed to pull, or your own identity?

**Comment by bkamin29** [comment]
Hello Laurent,
this is the result of a docker pull command from my laptop but we encounter the same issue from Cloud RUN.
```
docker pull gcr.io/slo-generator-ci-a2b4/slo-generator:2.5.2                                                                                                                                                     
Error response from daemon: manifest for gcr.io/slo-generator-ci-a2b4/slo-generator:2.5.2 not found: manifest unknown: Failed to fetch "2.5.2" from request "/v2/slo-generator-ci-a2b4/slo-generator/manifests/2.5.2".
```

**Comment by lvaylet** [comment]
Can you try with `2.5.0` and `2.5.1`?

`2.5.2.` is indeed missing from the Container Registry.

**Comment by svenmueller** [comment]
I'm getting similar error from Google Cloud Run (the service was running before using the same version, now it stopped working)

```
Google Cloud Run Service Agent service-xzy@serverless-robot-prod.iam.gserviceaccount.com must have permission to read the image, gcr.io/slo-generator-ci-a2b4/slo-generator:2.3.4. Ensure that the provided container image URL is correct and that the above account has permission to access the image.
```

**Comment by lvaylet** [comment]
Hi @svenmueller, can you share the email(s) of the Service Account(s) that require access to the Container Registry? I also need the Google Workspace customer ID of your GCP Organization, as returned by `gcloud organizations list`.

For the record, I had to disable public access to the Container Registry after someone in South America generated a lot of traffic by pulling the whole images every 5 minutes. This incurred big charges on Google's side (like 150 USD per day for egress alone). As I was unable to pinpoint the exact identity of the caller (it is an Amazon-owned IP), I decided to grant permissions on a case-by-case basis.

**Comment by lvaylet** [comment]
@bkamin29 Any news to share regarding `2.5.0` and `2.5.1`?

**Comment by bkamin29** [comment]
> Can you try with `2.5.0` and `2.5.1`?
> 
> `2.5.2` is indeed missing from the Container Registry.

confirmed, 2.5.0 and 2.5.1 are working

**Comment by lvaylet** [comment]
@svenmueller Feel free to share the details on my professional email (my username here, at google dot com) if you do not want to share them here.

**Comment by svenmueller** [comment]
@lvaylet Thx! I've sent an email as you've suggested.

**Comment by lvaylet** [comment]
@svenmueller Thanks a lot. I just granted the required permissions to your identities.
