### ISSUE TITLE
Issue when no good events with good_bad_ratio method

### ISSUE THREAD

**Issue by bkamin29** [google/slo-generator#42]
Hello,

When using `good_bad_ratio`, what happens if one of my two filter `filter_good` or `filter_bad` have No data available ?
For exemple if my service have no problems, `filter_good` have data but not `filter_bad`.
In this case and since the latest version of `slo-generator`, no SLI results are computed and sent to Bigquery..

In my exemple i use this log-based-metric :

```
resource "google_logging_metric" "quality_count" {
  name        = "nfs/quality_count"
  description = "Metric based on logs provided by the Cypress Cronjob. Used to compute quality SLO on NFS"
  filter      = "resource.type=\"k8s_container\"\nresource.labels.container_name=\"crj-sre-homepage-fr\"\njsonPayload.country=\"fr\""
  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
    unit        = "1"
    labels {
      key         = "platform"
      value_type  = "STRING"
      description = "nfs environment"
    }
    labels {
      key         = "status_code"
      value_type  = "INT64"
      description = "status code"
    }
    labels {
      key         = "country"
      value_type  = "STRING"
      description = "country code"
    }
    labels {
      key         = "page"
      value_type  = "STRING"
      description = "page name"
    }
  }
  label_extractors = {
    "country"     = "EXTRACT(jsonPayload.country)",
    "page"        = "EXTRACT(jsonPayload.page)",
    "platform"    = "EXTRACT(jsonPayload.platform)",
    "status_code" = "EXTRACT(jsonPayload.status)"
  }
}
```

and my slo_definition is :

```
slo_definition:
  slo_name:        quality
  service_name:    nfs
  feature_name:    fr-hp
  slo_description: quality on nfs fr home page
  slo_target:      0.999
  backend:
    class:         Stackdriver
    project_id:    ${PROJECT_ID}
    method:        good_bad_ratio
    measurement:
      filter_good:
        resource.type="k8s_container"
        metric.type="logging.googleapis.com/user/nfs/quality_count"
        metric.label.page="homepage"
        metric.label.country="fr"
        metric.label.status_code=1
      filter_bad:
        resource.type="k8s_container"
        metric.type="logging.googleapis.com/user/nfs/quality_count"
        metric.label.page="homepage"
        metric.label.country="fr"
        metric.label.status_code=0
```

From [monitoring/metrics-explorer](https://console.cloud.google.com/monitoring/metrics-explorer), `filter_bad` have no results because not yet logs have `status_code=0` 

My proposition is : Why not send SLI data when one of the two filter have data ?

**Comment by ocervell** [comment]
Working on a solution to set a threshold `MINIMUM_VALID_EVENTS` to skip SLO computation if we're under. Currently we don't send the report if the SLI value is 0, but we should reason in query volume. Will also add some disclaimer in the documentation stating the issue.

In the meantime, I encourage you to read "Low-Traffic Services and Error Budget Alerting" section which basically states that to have meaningful SLI / Error Budget / Burn rate values, we need to generate test load on our services that will ensure that there is enough data to compute those values - especially during periods with little traffic (night time or work hours for instance).
