### ISSUE TITLE
🐛 [BUG] - Datadog backend -> good_bad_ratio method

### ISSUE THREAD

**Issue by maximepln** [google/slo-generator#478]
### SLO Generator Version

image: slo-generator:2.6.0

### Python Version

3+

### What happened?

While trying to implement a Latency SLO on a log based metric with the good_bad_ratio method. 

We encounter a bug without any workaround, the following line defined in the [datadog-backend](https://github.com/google/slo-generator/blob/b6c50be1f55bf04bba80c1978d040cc6bf54a7d6/slo_generator/backends/datadog.py#L61) make it impossible to use distinct method to count events and therefore impossible to create the SLO itself.

To illustrate my point, such definition are impossible:
```
    method: good_bad_ratio
    service_level_indicator:
    query_good:  >-
      count(v: v<=1):http.nginx_ingress.logs_based_latency{service:myservice
      AND method:post
      AND env:production
      AND ((path:pathOR path:v1/path) AND NOT path:*path*)
      AND (status_code:2* OR status_code:3*)} 
    query_valid: >-
      count:http.nginx_ingress.logs_based_latency{service:myservice
      AND method:post
      AND env:production
      AND ((path:path OR path:v1/path) AND NOT path:*path*)
      AND (status_code:2* OR status_code:3*)}
```

### What did you expect?

Not having the `operator` and `operator_suffix` overload when they are already set in the query

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocervell** [comment]
Did you try to remove the `/` at the end of the first query and set `operator: null` in your config ?

**Comment by maximepln** [comment]
Hello there, 

The slash was a typo, sorry about that.

I tried with the `operator: null` and it worked ! It wasn't clear in the documentation that, this kind of option was available.

Thanks,
