### ISSUE TITLE
Dynatrace backend count method

### ISSUE THREAD

**Issue by clement-pruvot** [google/slo-generator#86]
In the Dyantrace backend count method, why do you use `return sum(values) / len(values)` ? It averages the number of events and flaws the SLO calculation (and it also returns a float sometimes).

As the Dynatrace API request returns a list with the number of events for each timestamp, we should just sum them.

The fix would be to just `return sum(values)`

(NB : I don't have the right to create a new branch and ask for a PR on this repo :( )

**Comment by ocervell** [comment]
Do you have an example where the calculation is flawed ? We do the same for Datadog and it gives the right SLI value (same as  the `query_sli` method or the `query_slo` method).

The reason we do this is to aggregate on multiple dimensions (labels) if they are not filtered in the metric selector.

**Comment by clement-pruvot** [comment]
In my example SLO stays the same you're right.
But the events number are different : 
With `return sum(values) / len(values)` : 
`slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | a.Last 1 hour | SLI: 100.0   % | SLO: 95.0 % | Gap: +5.0  % | BR: 0.0 / 9.0 | Alert: 0 | Good: 4190     | Bad: 0       
slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | b.Last 12 hours | SLI: 100.0001 % | SLO: 95.0 % | Gap: +5.0  % | BR: -0.0 / 3.0 | Alert: 0 | Good: 12976    | Bad: 0       
slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | c.Last 7 days | SLI: 99.9937 % | SLO: 95.0 % | Gap: +4.99 % | BR: 0.0 / 1.5 | Alert: 0 | Good: 57760    | Bad: 3       
slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | d.Last 28 days | SLI: 99.9983 % | SLO: 95.0 % | Gap: +5.0  % | BR: 0.0 / 1.0 | Alert: 0 | Good: 343201   | Bad: 5 `
With `return sum(values)` : 
`slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | a.Last 1 hour | SLI: 100.0   % | SLO: 95.0 % | Gap: +5.0  % | BR: 0.0 / 9.0 | Alert: 0 | Good: 250072   | Bad: 0       
slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | b.Last 12 hours | SLI: 100.0   % | SLO: 95.0 % | Gap: +5.0  % | BR: 0.0 / 3.0 | Alert: 0 | Good: 1879304  | Bad: 0       
slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | c.Last 7 days | SLI: 99.9937 % | SLO: 95.0 % | Gap: +4.99 % | BR: 0.0 / 1.5 | Alert: 0 | Good: 9759236  | Bad: 615     
slo_generator.compute - INFO - 08B84450B7CC1973/api/avail       | d.Last 28 days | SLI: 99.9983 % | SLO: 95.0 % | Gap: +5.0  % | BR: 0.0 / 1.0 | Alert: 0 | Good: 38779488 | Bad: 650`

**Comment by ocervell** [comment]
Ok; seems like the ratio doesn't change but the good, bad are different. 

Do you confirm that the second set of results correspond to the observed number of requests to your service ?
